meta_product_name: "Rent a Garden"
meta_title: "Rent a Garden - Find gardens near you"
meta_description: "Find the perfect garden to host your next party! Cheapest gardens near you are one click away."
meta_image: "gardencover.png"
